from flask import Flask, request, send_from_directory, abort
from werkzeug.utils import secure_filename
import scrypt
import flask_cors as flco
import os
try:
    from torf import Torrent # to disable turning swf into torrent files pip uninstall torf or dont install it at all
    # it wont work without seeders or running seed.py and there arent any trackers included in the file
    # if youd like to you can tho
except:
    print("the torf module was not found! swf files uploaded will not turn into torrent files")

app = Flask(__name__)
flco.CORS(app)
if not os.path.exists("db/swf/largestid.txt"):
    with open("db/lid/largestid.txt", "w") as f:
        f.write("0")
        f.close()
@app.route('/api/upload', methods=['GET', 'POST'])
def upload_file():
    if request.method == 'POST':
        f = request.files['flash']
        fname = request.form['fname']
        if not secure_filename(f.filename).endswith(".swf"):
            return "rejected: file type incorrect"
        with open("db/lid/largestid.txt", "r") as grf:
            num = int(grf.read())
        thenumber = num + 1
        if num == "0":
            thenumber = 1
        f.save(f"db/swf/{thenumber}.swf")
        with open(f"db/swfnames/{fname}.txt", "w") as fnf:
            fnf.write(f"swf/{thenumber}.swf")
        with open("db/swf/largestid.txt", "w") as grftw:
            grftw.write(str(thenumber))
        t = Torrent(path=f"db/swf/{thenumber}.swf", comment='This torrent file was generated by Torf automatically via a Swffy server.')
        t.generate()
        t.write(f'db/torrents/{thenumber}.torrent')
        return "Submitted! An admin will review your file and approve or reject it. You won't be notified if it is accepted or rejected."

@app.route('/api/getswf', methods=['POST'])
def getswf():
    jsonswf = request.get_json()
    swfname = jsonswf['swfname']
    print(swfname)
    print('../user/db/swf/' + swfname + ".swf")
    return {"swfpath": f"../user/db/swf/{swfname}.swf"}

@app.route('/api/delete')
def approve():
    password = request.form['passw']

@app.route('/api/signin', methods=["POST"])
def signin():
    pw = request.form['passw']
    try:
        with open("adminpw.bin", "rb") as f:
            realpw = f.read()
            f.close()
        g = scrypt.decrypt(realpw, pw)
        print("DECRYPTED:" + str(g))
        executed = True
        realpw = "abcdefgh"
    except Exception as e:
        realpw = "abcdefgh"
        print(str(e))
        abort(401, "Password incorrect")
    if executed == True:
        realpw = "abcdefgh" #what
        #to get rid of the variable
        #o
        return "success", 200
    
@app.route('/api/getswfdir', methods=["GET"])
def gsd():
    swfd = os.listdir("db/swf/")
    return swfd